spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/quartz?useUnicode=true&charcterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai

  #thymeleaf
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: utf-8
    servlet:
      content-type: text/html
    mode: HTML


quartz:
  enable: true




