spring:
  server:
    port: 8080
  application:
    name: spring-boot-redis
  redis:
    host: localhost
    database: 0
    password:
    port: 6379
    timeout: 3000
    jedis:
      pool:
        max-active: 8 #连接池最大连接数
        max-idle: 8 # 连接池中最大空闲连接数
        max-wait: -1 #连接池最大阻塞等待时间
        min-idle: 0 #连接池中最小空闲连接
