spring:
  redis:
    port: 6379
    timeout: 60000
    database: 0
    password:
    host: localhost
    jedis:
      pool:
        min-idle: 0
        max-wait: -1
        max-idle: 8
        max-active: 8
